# Introduction {#sec-introduction}

Activity-based models (ABMs) have been championed by researchers and many practitioners as being theoretically superior to the trip-based models historically used in transportation planning efforts since the 1950s [@rasouli_activity-based_2014].
ABMs explicitly model individuals, in contrast to the aggregate nature of trip-based models, and so in theory are able to represent travel behavior more accurately.
Additionally, the focus on individuals in an ABM can allow for more detailed post-hoc analysis of model outputs compared to a trip-based model.

There have been a number of comparisons and case studies between trip- and activity-based models [see e.g. @ferdous_comparison_2012; @zhongComparativeAnalysisTraditional2015; and @mouwComparisonAggregatedMacroscopic2022], but these comparisons focus almost exclusively on the technical ability of the two model types.
Though there are potential *theoretical* benefits to ABMs over trip-based models, there is little discussion in the literature of the *practical* benefits an ABM has, if any.
In fact, while trip-based models are almost ubiquitous among transportation agencies, many agencies have delayed or declined to transition to an ABM citing additional data requirements, staff training, computational resources, and related concerns [@miller_current_2023].

In this research, we perform a more holistic comparison of ABMs to trip-based models, with a particular focus on the practical considerations an agency would need to make in transitioning to an ABM.
We additionally discuss the potential practical advantages regarding the quality and characteristics of travel analyses that an ABM allows.
Though this research occasionally makes quantitative comparisons between model types, we do not focus heavily on model *accuracy* (either to each other or to observed data), as this can be adjusted in any model type through model calibration.
Instead, this research seeks to illustrate the differences between trip- and activity-based models in a way that would be practically useful to an agency considering transitioning to an ABM, noting potential pain points both in the literature and in our experience in this research itself.

To compare the model types, we first identify three main goals of travel demand modeling, which are to model travel behavior in response to changes in land use, transportation infrastructure, and social/economic factors.
We then create three hypothetical model scenarios, one for each goal identified.
These scenarios are the addition of a new development, an increase in commuter rail service, and an increase in remote work, respectively.
Each of these scenarios is created in both a trip-based and activity-based model representing the Wasatch Front (Salt Lake City) region of Utah, USA. We discuss the process of implementing each scenario, as well as perform a variety of post-hoc analyses, for both model types.

The document proceeds in a typical fashion: @sec-literature provides an overview of the literature discussing the differences between trip-based models and ABMs, including the theoretical and analytical benefits of each framework.
@sec-methods first describes the models used in this research, namely the existing regional trip-based model and an activity-based model constructed to support research activities in the region; this section also describes the scenarios designed to test the usefulness and applicability of the different model frameworks.
Chapters [-@sec-landuse]--[-@sec-wfh] describe the findings from each scenario, alongside a discussion of related limitations and implications.
@sec-conclusions provides a summary of our findings and a discussion of our conclusions, along with a set of recommendations.
