
Layout

WFH is our scenario

Here are some things to consider with WFH modeling

Here is what we did and why
- trip-based
- activity based


# Scenario 3: Work From Home

With the onset of the COVID 19 pandemic, there were unprecedented numbers of people working from home [@bick_work_2021].
This scenario is an attempt to model an increase in people working from home, or telecommuting.
There has been much research, especially in recent years, on the implications of telecommuting.
While many MPOs have adjusted their models to account for telecommuting, and most models follow similar principles, it is not obvious what the best method is.
@bramberga_teleworking_2023 even suggested that considerations for teleworking should be on a case by case basis because there is no single best approach.
Before describing how we set up the telecommuting scenario for our research, we will first describe some general considerations we had based on what is in the literature.

## Telecommuting Considerations

The first thing to consider is the fact that different job types allow different levels of telecommuting [@yasenov_who_2020].
An office worker using a computer is much more capable to work from home than a construction worker.
This fact is something that has been considered for telecommuting in most travel demand models [@bramberga_teleworking_2023; @moeckel_working_2017; @sener_copula-based_2011].

Another consideration that may seem obvious is there will be less home-based work trips when more people are telecommuting.
What isn't as obvious is the idea that there may be more discretionary trips produced when people are able to telecommute.
There have been many studies on this subject, and, when comparing the results of each study, it is hard to tell if that really is the case. 
@kim_is_2017 talks about a "rebound effect" where travel behavior changes on the days people don't have to commute to work and they make more trips for different reasons.
In another study, @zhu_impact_2014 find that there are more miles traveled on the days people telecommute.
This could be due to the existence of a travel time budget, where an increase in trips of one purpose will decrease the time people allocate for trips of another purpose [@moreno_microscopic_2017].
Taking it a little further, @ellder_telework_2020 finds that distinguishing between people that work from home all day and part of the day might make a difference.
Compared to those who commute to work, the Sweden study shows that those who worked from home the whole day had less trips and miles traveled, but those who worked from home only part of the day had more trips and miles traveled.
Using data from the 2007 Chicago Regional Household Travel Inventory, @he_telecommuting_2015 found that, after adjusting for other factors like income, household size, and job industry, people who telecommute frequently make 0.072 more discretionary trips on average each day compared to those who don't telecommute. 
@mokhtarian_the_1998 saw opposite effects where vehicle miles traveled decreased for both work and discretionary trips on telecommuting days.
Because there isn't a solid conclusion on whether more discretionary trips are created as more people telecommute, we will not put that into the model. 

The last consideration we will discuss is the distance people are willing to travel when they telecommute.
@moeckel_working_2017 explains the correlation between the number of days people telecommute and the distance they are willing to live from their job.
If someone works completely remote, then they will have nothing forcing them to live close to their job.
If they only work one day a week in the office, then they are still willing to live farther away than someone who has to work in the office two or three days a week.
This information could change the trip length frequency distribution of home-based work trips.

To organize the main ideas of the literature, we kept in mind these three principles as we prepared the models:

-   Different employment types have differing levels of telecommuting

-   Home-based work trips decrease

-   There is a greater possibility that home-based work trips are longer 

The last principle mentioned has been used in other models [@moeckel_working_2017], but, due to the way the WFRC model is set up, we were unable to make a suitable change to reflect an increase in trip length frequency caused by telecommuting without changing the fundamental design of the model.  
The following sections will describe how we used the first two principles as we prepared the telecommuting scenario in each of the models. 

## Trip-based Model

In the WFRC trip-based model, it was already programmed to reduce home-based work trips using a telecommute percentage for each type of employment and a percentage of home-base jobs. 
We simply changed the telecommute and home-based job percentages to align with projections for 2050. which increased telecommute trips from 3.7 to 10.2 percent and increased home-based jobs from 2.9 to 3.5 percent.
If there was more guidance in the literature on how telecommuting affects other types of trips, then we could have tried to represent that in the model by adding a certain amount of discretionary trips according to the telecommute percentages.
With the \acr{WFRC} model, it might be difficult to have the additional discretionary trips be coming from the same zones as the telecommute trips. *(I'm not sure about this. I'll have to look more into it)*


## Activity-based model

wfh and telecommute_freq models, taken from SEMCOG prototype.
had to adjust to work with MTC, not too bad.
Also added job category coefficients to tf model, calibrated to wfrc percent (mention in methodology)
