project:
  type: book
  execute-dir: project

execute:
  echo: false
  warning: false
  # cache: refresh
  cache: true
  freeze: auto
pdf-engine: xelatex

layout: fancy, twoside, masters
department: Civil and Construction Engineering
student: Hayden Atchley
chair: Gregory S. Macfarlane
committee:
  - Grant G. Schultz
  - Gustavious P. Williams

# Title with custom formatting for fancy title page
customtitle: |
  | A Comparative Illustration of
  | Trip- and Activity-Based
  | Modeling Techniques
book:
  output-file: "A_Comparative_Illustration_of_Trip-_and_Activity-Based_Modeling_Techniuqes"
  title: |
    | A Comparative Illustration of Trip- and
    | Activity-Based Modeling Techniques
  author:
    - name: Hayden Atchley
      email: satchley@byu.edu
      orcid: 0000-0002-0815-3488
      affiliations:
        - ref: byucce
    - name: Kamryn Mansfield
      email: kamrynwm@student.byu.edu
      orcid:
      affiliations:
        - ref: byucce
    - name: Gregory S. Macfarlane
      email: gregmacfarlane@byu.edu
      orcid: 0000-0003-3999-7584
      affiliations:
        - ref: byucce
  date: "1 August 2024"
  date-format: D MMMM YYYY
  chapters:
    - index.qmd
    - qmd/lit-review.qmd
    - qmd/methods.qmd
    - qmd/1_land_use.qmd
    - qmd/2_transit.qmd
    - qmd/3_wfh.qmd
    - qmd/conclusions.qmd
    - qmd/references.qmd
  abstract: >-
    Over the last fifteen years, activity-based models have slowly
    replaced trip-based models as the standard tool used for planning and
    forecasting efforts in the United States. But the general adoption of
    activity-based models has been slowed by a number of factors, including
    real and perceived costs in terms of data availability, computational
    resources, and staff training for analysis. In this research, we explore
    the state of these considerations in light of newly developed open-source
    platforms for activity-based modeling. We do this by applying a trip-based
    model for the Wasatch Front region of Utah and an implementation of ActivitySim
    in the same region to analyze three scenarios common to transport planners:
    a change in land use, a change in transport infrastructure, and a change
    in underlying travel behavior.
    We find that the activity-based  approach allows for a more straightforward
    and intuitive interpretation of model results at little additional cost for scenario
    configuration, computation, or analysis. This suggests that some of the justifications
    for not adopting activity-based models may be outdated or irrelevant.

keywords:
  - travel demand model
  - activity-based model
  - ActivitySim
acknowledgments: >-
  I would like to acknowledge the Utah Department of Transportation for providing funding for this research.
  Additionally, I would like to thank the modeling teams at the Utah Department of Transportation, Wasatch Front Regional Council, Mountainland Association of Governments, and Fehr & Peers for their help and input at several stages of this project.
  I would specifically like to thank Chad Worthen and Chris Day at Wasatch Front Regional Council for answering my questions about their travel demand model.
  I would also like to thank my peers in the BYU transportation lab for their friendship and support, and especially for their help dealing with miscellaneous issues that arose throughout this project.
  Lastly, I would like to especially thank my graduate advisor, Greg Macfarlane, for his support and encouragement.

affiliations:
  - id: byucce
    name: Civil and Construction Engineering Department, Brigham Young University
    address: 430 EB
    city: Provo
    state: UT
    postal-code: 84602

format:
  # html:
  #   theme: cosmo
  trb-pdf:
    top-level-division: "section"
    include-in-header:
      - style/latex_preamble.tex
  byu-thesis-pdf:
    keep-tex: true
    highlight-style: arrow
    include-in-header:
      - style/latex_preamble.tex
    #   - style/tt_preamble.tex
    dpi: 900
    fig-dpi: 900
    mainfont: Gentium Book Basic
    sansfont: Alte Haas Grotesk
    monofont: SauceCodePro NF
    fig-width: 5
    fig-height: 5
    # out-width: 100%
    # out-height: 100%
    fig-format: png
  # html:
  #   theme: cosmo
  # docx:
  #   reference-doc: style/udot_template.docx
fig-align: center
number-depth: 2
toc-depth: 2
bibliography:
  - bib/references.bib
  - bib/packages.bib
csl: style/asce.csl

filters:
  - acronyms

acronyms:
  loa_title: ""
  insert_loa: false
  insert_links: false
  include_unused: true
  loa_header_classes:
    - unnumbered
  sorting: "alphabetical"
  non_existing: "??"
  style: "long-short"
  on_duplicate: "error"
  fromfile:
    - _acronyms.yml
