project:
  type: book
  
execute:
  echo: false

book:
  title: "abm_illustration"
  author:
    - name: Hayden Atchley
      email: satchley@byu.edu
      orcid: 0000-0002-0815-3488
      affiliations:
        - ref: byucce
    - name: Gregory S. Macfarlane
      email: gregmacfarlane@gmail.com
      orcid: 0000-0003-3999-7584
      affiliations:
        - ref: byucce
 
  date: "4/14/2023"
  date-format: DD MMMM YYYY
  chapters:
    - index.qmd
    - intro.qmd
    - lit-review.qmd
    # - lit-review_notes.qmd
    # - methods.qmd
    # - results.qmd
    # - discussion.qmd
    # - conclusions.qmd
    - references.qmd
 
affiliations:
  - id: byucce
    name: Civil and Construction Engineering Department, Brigham Young University
    address: 430 EB
    city: Provo
    state: UT
    postal-code: 84602
    
bibliography: bib/references.bib

lof: true
lot: true

format:
  html:
    theme: cosmo
  pdf:
    toc-depth: 3
    # template: template.tex
    # mainfont: Gentium Book Basic
    # sansfont: Alte Haas Grotesk
    # monofont: SauceCodePro NF
  docx:
    reference-doc: style/template.docx



