project:
  type: book
  execute-dir: project

execute:
  echo: false
  warning: false
  cache: refresh
  # cache: true
  # freeze: auto

book:
  title: "A Comparative Illustration of Trip- and Activity-Based Modeling Techniques"
  author:
    - name: Hayden Atchley
      email: satchley@byu.edu
      orcid: 0000-0002-0815-3488
      affiliations:
        - ref: byucce
    - name: Kamryn Mansfield
      email: kamrynwm@student.byu.edu
      orcid:
      affiliations:
        - ref: byucce
    - name: Gregory S. Macfarlane
      email: gregmacfarlane@byu.edu
      orcid: 0000-0003-3999-7584
      affiliations:
        - ref: byucce
  abstract: |
    "this is an abstract"

  date: "1 January 1900"
  date-format: D MMMM YYYY
  chapters:
    - index.qmd
    # - qmd/intro.qmd
    # - qmd/lit-review.qmd
    # - qmd/methods.qmd
    # - qmd/1_land_use.qmd
    - qmd/2_transit.qmd
    # - qmd/3_wfh.qmd
    # - qmd/conclusions.qmd
    # - qmd/references.qmd

affiliations:
  - id: byucce
    name: Civil and Construction Engineering Department, Brigham Young University
    address: 430 EB
    city: Provo
    state: UT
    postal-code: 84602

bibliography:
  - bib/references.bib
  - bib/packages.bib
lof: true
lot: true
fig-align: center
number-depth: 2
toc-depth: 2

format:
  # html:
  #   theme: cosmo
  pdf:
    keep-tex: false
    # template: style/template.tex
    include-in-header:
      - style/latex_preamble.tex
      - style/tt_preamble.tex
    # dpi: 900
    # fig-dpi: 900
    # mainfont: Gentium Book Basic
    # sansfont: Alte Haas Grotesk
    # monofont: SauceCodePro NF
    fig-width: 8
    fig-height: 12
  # docx:
  #   reference-doc: style/template.docx

filters:
  - acronyms
  # - abstract-section

acronyms:
  loa_title: ""
  insert_loa: false
  insert_links: false
  include_unused: true
  sorting: "alphabetical"
  non_existing: "??"
  style: "long-short"
  on_duplicate: "error"
  fromfile:
    - _acronyms.yml

# abstract-section:
#   section-identifiers:
#     - abstract
