project:
  type: book
  execute-dir: project

execute:
  echo: false
  warning: false
  cache: refresh
  # cache: true
  # freeze: auto
pdf-engine: xelatex

layout: fancy, twoside, masters
department: Civil and Construction Engineering
student: Hayden Atchley
chair: Gregory S. Macfarlane
committee:
  - Grant G. Schultz
  - Gustavious P. Williams

# Title with custom formatting for fancy title page
customtitle: |
  | A Comparative Illustration of
  | Trip- and Activity-Based
  | Modeling Techniques
book:
  output-file: "A_Comparative_Illustration_of_Trip-_and_Activity-Based_Modeling_Techniuqes"
  title: |
    | A Comparative Illustration of Trip- and
    | Activity-Based Modeling Techniques
  author:
    - name: Hayden Atchley
      email: satchley@byu.edu
      orcid: 0000-0002-0815-3488
      affiliations:
        - ref: byucce
    - name: Kamryn Mansfield
      email: kamrynwm@student.byu.edu
      orcid:
      affiliations:
        - ref: byucce
    - name: Gregory S. Macfarlane
      email: gregmacfarlane@byu.edu
      orcid: 0000-0003-3999-7584
      affiliations:
        - ref: byucce
  date: "1 January 1900"
  date-format: D MMMM YYYY
  chapters:
    - index.qmd
    - qmd/intro.qmd
    - qmd/lit-review.qmd
    - qmd/methods.qmd
    - qmd/1_land_use.qmd
    - qmd/2_transit.qmd
    - qmd/3_wfh.qmd
    - qmd/conclusions.qmd
    - qmd/references.qmd
  abstract: >-
    this is an abstract

keywords:
  - travel demand model
  - activity-based model
  - ActivitySim
acknowledgments: >-
  Students should acknowledge funding sources.
  They may also use the acknowledgment page to express appreciation
  for the committee members, friends or family who provided support or
  aided the research, writing or technical aspects of the thesis/dissertation.
  Acknowledgments should be simple and in good taste.

affiliations:
  - id: byucce
    name: Civil and Construction Engineering Department, Brigham Young University
    address: 430 EB
    city: Provo
    state: UT
    postal-code: 84602

format:
  byu-thesis-pdf:
    keep-tex: true
    highlight-style: arrow
    include-in-header:
      - style/latex_preamble.tex
    #   - style/tt_preamble.tex
    dpi: 900
    fig-dpi: 900
    mainfont: Gentium Book Basic
    sansfont: Alte Haas Grotesk
    monofont: SauceCodePro NF
    fig-width: 5
    # fig-height: 5
    # out-width: 100%
    # out-height: 100%
    fig-format: png
  # html:
  #   theme: cosmo
  # docx:
  #   reference-doc: style/udot_template.docx
fig-align: center
number-depth: 2
toc-depth: 2
bibliography:
  - bib/references.bib
  - bib/packages.bib
csl: style/asce.csl

filters:
  - acronyms

acronyms:
  # loa_title: ""
  insert_loa: false
  insert_links: false
  include_unused: true
  loa_header_classes:
    - unnumbered
  sorting: "alphabetical"
  non_existing: "??"
  style: "long-short"
  on_duplicate: "error"
  fromfile:
    - _acronyms.yml
