# lit review notes

***(outline)***

The Review should explore analyses done by others using either a trip- or activity-based model. It should focus on the types of analyses that can be done with either kind of model, in particular noting when a certain analysis is made easier or even possible by one or the other. There are several types of analyses that can be done:

- Equity: How does transportation impact minority and low-income groups?
  - *Bills et al., 2012*
  - *Bills and Walker, 2017*
  - Nahmias-Biran and Shiftan, 2016
  - Pereira et al., 2017
- Accessibility: What kinds of measures can we calculate, and how are they useful?
  - *Dong et al., 2006*
- Resilience? This might be just an assignment thing, but maybe it would have an influence on mode/destination choice?
  - Ganin et al., 2107

Possible analyses:

- Ridership (incl. by {stop|demographic|land use})
- Facility needs assessment
- Logsums?

@bills_looking_2017 present a framework for using activity-based models to analyze impacts on equity. This is a three-step process, which is to determine equity indicator(s) and how to segment the population, calculate the indicator(s) for each scenario, and compare these results relative to the base scenario. While much of this framework can be implemented in a trip-based model, the critical component is how the population is grouped in the first step. In a trip-based model, socioeconomic data is calculated at the TAZ level or similar, using a mean value for data like income and auto ownership. This mean, though, is likely to mask the heterogeneity of individual socioeconomic status and travel behavior within a single TAZ, and these differences can be important, especially for disadvantaged members of society. An activity-based model on the other hand *does* utilize socioeconomic data and model travel behavior at an individual level, so analyses aggregated by groupings such as race, income, and employment status can be much more precise.

@bills_activity-based_2012 make a similar observation, noting that since activity-based models use disaggregate data, equity indicators can be calculated at an individual level.

@dong_moving_2006 looks at several measures of accessibility, including isochrone, gravity and utility-based measures, and compares the so-called activity-based accessibility measure to these. They note that these first three types of measures are trip-based, and as such have no concept of trip chaining or scheduling. The activity-based accessibility measure, on the other hand, incorporates an individual's full daily travel pattern and reflects individual  socioeconomic characteristics as well as the land use and transportation network. As an example, a trip-based measure would ignore the change in commute scheduling some individuals would make if a peak-period toll were implemented on the network, while the activity-based measure would account for this change. The activity-based accessibility measure, though, requires travel modeling to be done at an individual level, so an activity-based model would be required over a trip-based model.

## Comparison of Modelling Frameworks

### Synthetic population vs aggregate data

Generally, survey data and various models can determine the average of several metrics for a TAZ, and determine cross-classifications and segmentations (e.g. if there are 100 hh and an avg of 1 veh/hh in a TAZ, there could be 25 0-veh hh, 50 1-veh hh, and 25 20veh hh). This can in theory be segmented by income, race, job status, gender, etc. if analyses are desired on these groups, but that presents two problems. One is that trip generation rates are required for each cross-classification, so while a 2-way cross-classification may have on the order of 10 trip production rates, a multi-way cross-classification may have orders of magnitude more rates. Additionally, as the number of factors increases, these rates have wider margins of error as the sample size drastically decreases.

A synthetic population uses census and other data to create a simulated population of households that is representative of actual households without violating privacy. This takes aggregate data in small geographical delineations and combines that with specific household data in large geographical delineations to produce a representative population that can be used for analysis. Trip production is then done via regression or similar rather than summary statistics. This also has the advantage that analyses can be done with groupings that were not taken into account in the model, e.g. if race is a characteristic noted in the population, analysis grouped by race can be done even if race is not a factor in mode/destination choice and/or trip generation. With summary statistics this is impossible since it's not clear who made which trips unless these factors are a part of each step.

### Trip-based

Trip based usually uses summary statistics, so runs into the over-segmentation problem when certain analyses are attempted. Even if a synthetic population is used in a trip-based model, this data is used mainly for access to more variables in utility and regression eqns. While we can say that a specific person made specific trips, there's not a coherent way to chain these trips together, and these trips are usually grouped by time of day rather than using specific times for each trip **<< fact-check this >>**.

### Activity-based

ABMs use synthetic populations, so have the advantages thereof. They also chain an individual's trips together in a day, and these trips and activities are given specific times. For example, a person cannon drive to lunch and back from work if they took the bus to work, since they do not have a car at work. A trip-based model doesn't care about this.

## Claimed Advantages

See paragraphs on @bills_looking_2017, @bills_activity-based_2012, and @dong_moving_2006 above. Except rewrite these and expound on them. What types of analyses did they do? Why is it meaningful? What did they *not* do? Was the type of model used required, or why did they use it?

## Research Gap

While people have looked at advantages of ABMs for modeling and analyses, no one has yet done a side-by side methodological comparison of the two (i.e. running the same scenario(s) and analysis(es) in both types of models and comparing the process). **<< Is this true? >>**