# Literature Review

Travel demand modeling in the modern sense has its origins in the 1950s, with the Chicago Area Transportation Study [@chicago_area_transportation_study_final_1959] being one of the first urban planning studies to use the now-ubiquitous "four-step" modeling framework [@mcnally_four-step_2007].
Up until this point, most urban transportation planning used existing demand or uniform-growth travel forecasts to model travel demand, but the Chicago Study used a combination of trip generation, trip distribution, modal split, and network assignment models to more accurately represent travel behavior [@weiner_urban_1997].
Since then, there have been numerous studies iterating on the "four-step" (more appropriately termed "trip-based") framework [@cite?], and models of this type are now used in forecasting travel demand across the United States [@park_intrazonal_2020].

These trip-based models are not without problems, however.
@rasouli_activity-based_2014 give several shortcomings of trip-based models: they use several sub-models that are (implicitly or explicitly) assumed independent, and this can result in a lack of consistency or integrity between sub-models; they are strongly aggregated in nature, which can cause significant aggregation bias; and they lack "behavioral realism"---that is, they do not have a concept of individuals making decisions, which is what travel behavior actually is.

@jones_new_1979 proposed an alternative to the trip-based paradigm, namely an "activity-based" framework that models daily activity patterns at an individual rather than aggregate level.
Activity-based models (ABMs) place the focus on "activities" rather than "trips" as the basic unit of analysis, and predict a sequence of activities for each individual and household, with information such as activity location, start time, and duration, using a high level of temporal and spatial granularity.
"Trips" are then the result of getting from one activity to the next [@pinjari_activity-based_2011].
By adopting this activity-centric framework, ABMs provide a more consistent and comprehensive representation of travel behavior.
They take into account complex dependencies and interactions within the model as a whole and at an individual level.
ABMs acknowledge that travel choices are not made in isolation, but rather influenced by the preceding activities.
This means that e.g. if an individual takes transit to work, they will not be able to drive home.
ABMs therefore present a more conceptually accurate model of actual travel behavior than traditional trip-based models.

Despite these advantages, however, many agencies have yet to adopt ABMs, instead continuing to use trip-based models [@miller_current_2023].
While ABMs are superior in certain aspects, they also have disadvantages, such as requiring more detailed input data and greater computational resources.
It is also not always clear if ABMs provide substantially better forecasts than their trip-based counterparts, nor if this tradeoff is worth it for every agency.
This literature review presents an overview of both modeling frameworks, and discusses the potential advantages and disadvantages of using an ABM.

## Overview of Model Types

(Maybe we use the same NCHRP716 manual to cite most all of this section? @transportation_research_board_travel_2012)
Trip-based models are often referred to as "four-step" models due to their four fundamental sub-models: trip generation, trip distribution, mode choice, and network assignment [@citeNCHRP716, 28].
Trip-based models are often more complicated than this, possibly including integration with a land use forecast, iteration between mode and destination choice, etc., but the "four steps" are the central component of any of these models [@cite].
(pg. 92 of the NCHRP 716 talk about three broad steps in ABMs. 1. Population synthesis; 2. Long-term choice models: and 3. Activity-based travel models.)(maybe we should include this here?)

In a typical trip-based model, travel demand is predicted based on aggregate population data, often delineated by transportation analysis zones (TAZs).
Each sub-model relies on this aggregate data; for example, the modal split sub-model will often use average TAZ income as an input [@citeNCHRP716, 14].
The output of the first three of the four steps is a set of trip matrices, usually separated by mode and possibly time of day.
These matrices list the number of trips between each TAZ, and these trips are then assigned to a transportation network [there are various algorithms for doing so, see @cite].

Activity-based models differ significantly from this approach.
Rather than using aggregate data, ABMs use an actual or synthetic population, with individual person and household data [@cite].
These models use an activity or tour scheduler to assign a daily activity pattern (DAP) of zero or more tours to each individual (*n.b.* a tour is a series of trips that begin and end at home).
These DAPs are restricted temporally, spatially, and modally; i.e., each person has a logical and followable sequence of trips and activities [@cite].
A "drive alone" trip from work to lunch, for example, cannot be made if transit was taken to work.
ABMs output a list of tours and trips by person, time, location, and type, and these can then be assigned to a transportation network in a similar manner as in a trip-based model.

## Comparison of Modeling Frameworks

In discussing the differences between ABMs and trip-based models, there are really two comparisons that need to be made: how the population data is structured, and how travel is organized.
Trip-based models generally use aggregate population data while ABMs use a synthetic population, and trip-based models organize travel into trips while ABMs organize travel into activities and tours.
The following sections will explain these different aspects of travel demand modeling and discuss the claimed advantages and disadvantages of each.

### Aggregate Population vs. Synthetic Population

The aggregate population data used in trip-based models can be varied in origin and level of detail, but the basic concept is the same: the study area is organized into generally small zones, and certain demographic and socioeconomic data is known or obtained for each zone [@transportation_research_board_travel_2012, 14].
This includes data such as number of households, average household income, population, and number of workers, etc.
Based on this information, the zone can be segmented along arbitrary variables.
For example, since households with more workers and more vehicles tend to make more work trips, it is useful to estimate the distribution of households in each zone along these two variables.
Then, average trip production rates are determined for each household category (e.g. for households with each number of workers by vehicles), and the total number of trips produced in a zone is calculated based on these rates [@transportation_research_board_travel_2012, 37].

This approach is relatively straightforward: the required input data is usually easy to obtain, the trip generation models are often simple, and it is computationally inexpensive [@cite].
However, using aggregate data also has significant drawbacks, especially from an analysis perspective.
There is no way to know who is making which trips without explicitly coding the relevant variables into each sub-model.
For something like an equity analysis, for example, it is impossible to predict the "winners" and "losers" of a potential policy without using race/income/etc. as variables in the trip generation and destination and model choice steps [@cite].
This is problematic; while there is data on trip rates, mode choice, etc. by race, if this is coded into the model then the model asserts that these trends will hold no matter the policy implementations.

As an added complication to the difficulty of these analyses, the aggregate population data must from the start be segmented along each analysis variable.
An analysis based on parents'/adults' highest received education, for example, would require determining the number of households in each TAZ with each possible combination of education level.
This can be done, but more detailed and varied analyses would require more segmentation, exponentiating**?** the number of classifications needed.
Since these variables need to be carried through each model step, trip rates etc. need to be estimated for every classification, and while real-world data may exist, sample sizes approach zero very quickly, and so the estimates have little statistical value [@cite?].
(Maybe cite the NCHRP 716 again. pg 14 says "These data form the foundation of the model for an area, and if they do not meet a basic level of accuracy, the model may never adequately forecast travel.")

An alternative approach to population data is to use a full synthetic population.
A synthetic population takes demographic and socioeconomic data at various levels of detail to create a "population" with generally the same distribution as the study area [@transportation_research_board_travel_2012, 93].
The goal is to have a population that is functionally similar to the actual population, but without the privacy concerns of using real individual household data.
@castiglione_application_2006 argues that the major advantage with this approach is that the demographic and socioeconomic data is known at the person and household level, rather than the zone level, and this data remains available throughout the modeling process.
This allows, for example, an equity analysis to determine the "winners" and "losers" of a proposed development without needing to encode race/gender/etc. into each step of the model.

@bills_looking_2017 for example who used the 2000 Bay Area Travel Survey to create a synthetic population and compare the effects that certain scenarios had on high income and low income populations.
With a 20% reduction in travel cost, they saw that high income workers benefited more than low income workers.
They did similar comparisons for scenarios involving reduced travel times for different mode choices and were able to see the effects each scenario had on the high and low income workers.
These types of analysis, which are not possible with an aggregate population, can be very valuable in transportation planning and policy making. 

It is important to note that, while many connect them with ABMs, synthetic populations can be used in running trip-based models as well.
Trip-based models using a synthetic population---often called trip-based microsimulation models---do exist [see e.g. @walker_making_2005 and @moeckel_agent-based_2020], but these are relatively rare.
If a company is willing to go through the initial work of creating a synthetic population, then they may jump straight to an ABM because they believe it will be most accurate.

@fig-popdata-flowchart gives a visualization of an example "information pipeline" for a trip-based model using aggregate data and one using a synthetic population.
In the aggregate data model, it is impossible to know which trips are made by e.g. 2-worker, 1-vehicle, low-income households, only which trips are made by households with fewer vehicles than workers.
With a synthetic population, however, *individuals* are being modeled, and so each trip can be traced to a specific person.
All information is known at each point in the model regardless of which data is used in previous steps.

```{r}
#| label: fig-popdata-flowchart
#| fig-cap: "Example information pipelines for two theoretical trip-based models, one using aggregate data and another using a synthetic population."
#| fig-scap: "Example information pipelines for aggregate data and synthetic population."
#| fig-subcap: 
#|   - "Aggregate data"
#|   - "Synthetic population"
#| layout-ncol: 2

plot(mtcars$mpg, mtcars$wt)

plot(Orange$age, Orange$circumference)
```

### Trips vs. Tours

The other significant difference from trip-based models ABMs have (and the main difference from trip-based microsimulation models) is that ABMs organize travel into "tours", a sequence of trips that begin and end at the home, rather than just trips.
In fact, @miller_current_2023 points out that many current "activity-based" models ought to rather be labelled "tour-based" due to this focus on building tours.
This is contrasted with "activity scheduling" models, in which activity participation is modeled explicitly and trips emerge as the means to get from one activity to the next.
However, in practice there are few true "activity scheduling" models, and the term "activity-based" is used to refer to both these and "tour-based" models.
*extra sentence?*

In a typical trip-based model, trips are forecasted based on empirical trip rates, usually by trip purpose and by household type (for example, 1-worker, 2-vehicle households make a certain number of "home-based work" trips) [@cite].
These trips are then assigned an origin and destination, mode, and often a time of day (peak/off-peak, etc.), and the result is a list of trips between each zone by mode and purpose.
A trip-based microsimulation model may use regression models rather than aggregate data for some of the model steps [@cite], but the end result is similar: a list of trips by person, noting mode and purpose.
@cite point out, though, that this trip list may be inconsistent, and the forecasted trips may not be physically possible to complete in any sequence.
However, (they) note, the hope is that over an area the inconsistencies would "cancel out", leaving an overall accurate forecast.

ABMs, on the other hand, model *tours* rather than trips.
This allows for consistency in trip origins/destinations, mode choice, and time of day: since each trip is a part of a "chain" (tour), the trips within a tour are dependent on each other [@rasouli_activity-based_2014].
The open-source ABM ActivitySim [@cite], as an example, has a tour-scheduling model that determines the number of "mandatory" (work, school, etc.) and "discretionary" tours each individual will make, and performs tour-level mode and destination choice for each tour.
After the tour-level decisions are made, trip-level mode/destination choice is done for each trip in the tour, including the possible addition of subtours (e.g. leaving work for lunch).

@rasouli_activity-based_2014 also note that ABMs can model dependencies between members of a household as well.
A vehicle can't be used by multiple people in the same household at the same time to travel to different destinations.
Because the people within the household will have travel patterns that depend on the patterns of others in the household, a policy affecting one person in the household can affect everyone in the household no matter how directly the policy connects to them.
These effects aren't possible to forecast in a trip-based model.

Another advantage of organizing travel into tours comes regarding accesibility analyses.
@dong_moving_2006 note that when trip-based models are used to analyze accessibility, each zone must be analyzed independently of travel behavior.

For example, "total number of employment opportunities within 30 minutes by transit."
Accessibility with ABMs is calculated as a function of all activities pursued throughout the day, which goes much further than trip based models.
Along with having a spatial dimension to the accessibility function, ABMs also provide a dimension of individuality.
ABMs take into consideration that different groups of people have different levels of accessibility whereas trip based models wouldn't be able to make that consideration.
An ABM would group young college students and retired 70-year-olds differently while trip-based models would group them together.
In their study, @dong_moving_2006 found that ABMs predict more reasonable accessibility outcomes.
With the ABM, unemployed people were not as affected by a toll than those who needed to drive to work, and, similarly, those without a car were less affected by a toll than those with a car. 

## Why aren't ABMs used more often?
If ABMs are believed to be more accurate, one may wonder why there are so many MPOs that don't make the switch away from trip based models.
There has been a lot of research done on the subject, and many models have been developed.
Some notable ABMs are ADAPTS[@auld_activity_2012], ALBATROSS[@arentze_learning-based_2004], CEMDAP[@bhat_comprehensive_2004], FAMOS[@pendyala_florida_2005], FEATHERS[@bellemans_implementation_2010], MATSim[@horni_multi-agent_2016], and TASHA[@miller_prototype_2003].
@miller_current_2023 gives some ideas for why there is a gap between the academic interest of ABMs and the implementation into mainstream operational planning practice.
Possible reasons ABMs have not been implemented include the following:

Computational inefficiency and complicated program design:
As explained in previous paragraph, ABMs take more time, more computing power, and more money to run.
This is because the synthetic population needed to run an ABM uses much more data.
In areas with thousands of TAZs and millions of people, a super computer is needed, and it will cost much more than what is spent to run trip based models.
If a city can see similar results using a trip based model, they may decide not to invest in an ABM.

Absence of a standard model system:
The modeling systems are often designed with different approaches and for specific areas making it hard to transfer from one urban area to another.
This also makes it difficult for agencies to determine which approach is the best and decide which to implement.
In relation to this, Miller also states that the pressures of publishing unique and ground-breaking research in academia can deter researchers from converging towards best theories and methods.

Lack of resources:
Most of these models were developed in academic settings which often lack resources, and possibly desire, to put them into practice.
This leaves it up to governments and consultants to put the models into practice, but they can be hesitant to promote software development and to invest in new systems.

## Research Gap

Though there has been much research on ABMs and their theoretical advantages, to the authors' knowledge there is little in the literature about their practicality in the real world.
It is often taken as given that ABMs are unilaterally superior to traditional trip-based models due to their better theoretical foundation, but it is not clear if that better foundation always yields better results.
@ferdous_comparison_2012 compared the trip- and activity-based model frameworks of the Mid-Ohio Regional Planning Commission and found that the ABM performed slightly better at the region level, but about the same at the project level.
*If this is true more generally, an agency may have no real need to switch to an ABM over their current trip-based model since the improvement in results may not outweigh the increase in data, computational, training, and potentially financial requirements.*

@ferdous_comparison_2012, however, mainly compared the *accuracy* of the two frameworks, but did not address the methodological differences between them.
What types of data collection/synthesis are needed for each model type?
Are there analyses that can only be done through (or that are made easier by) one of the model types?
What would an agency need in order to transition from a trip-based model to an ABM?
Are certain types of scenarios suited to one model type?
Though some of these questions have been discussed [see e.g. @lemp_aggregate_2007], a holistic methodological comparison is lacking.
Additionally, the answers in the current literature are mainly theoretical, with little use to an agency considering the transition.

This research aims to answer these questions by providing a side-by-side comparison of a potential trip-based and activity-based modeling methodology.
Several "proposed development" scenarios are run in each model, and the strengths and weaknesses of each approach are compared.
It is important to note that this paper is not focused on model accuracy, as in any model type this can be adjusted dramatically through calibration efforts.
Rather, the focus is on the methodological differences between the approaches, and the types of analyses that can be done with each model type.
