# Introduction

In the last decade, numerous peer regions and states have adopted a new
approach to travel demand modeling by transitioning from traditional “trip
based” methodologies to “activity-based” frameworks. While traditional
trip-based models generate trips between zones based on aggregate productions
and attractions, activity-based models simulate individual households and
travelers seeking to access various destinations over the course of a day.
Activity-based models capture peoples’ choices and constraints more
realistically [@rasouli2014], and therefore can better represent pricing (e.g.
managed lanes), provide more realistic representation of non-home-based trip
making, and give forecasters the ability to consider project benefits and
impacts at a finer resolution than is possible with a trip-based model
[@bills2012]. Additionally, activity-based models are better able to represent
or support innovative transportation modes, complex public transit path
choices, the effects of travel time reliability in trip making and destination
choices, and dynamic network assignment procedures.

Many of UDOT’s peer agencies have transitioned to activity-based models,
including the Oregon and Idaho departments of transportation and the Denver,
Portland, Seattle, and Phoenix metropolitan planning organizations. At the same
time, the additional complication of methods and software implementations has
reportedly created additional costs for agencies and their contractors in terms
of staff training, computational resources, and model development and support
contracts. This research seeks to illustrate the tradeoffs of these modeling
approaches and help UDOT understand all relevant considerations to potentially
supporting an activity-based modeling framework.
